### ISSUE TITLE
Invisible caret in `contenteditable` with Firefox

### ISSUE THREAD

**Issue by pynnl** [elad2412/the-new-css-reset#14]
Reproduce: https://codepen.io/pynnl/pen/VwzOLpx

Tested on:
- Windows 10 Education x64 19042.1348
- Chrome 96.0.4664.45
- Firefox 94.0.2

It works fine on Chrome. However on Firefox, the caret is invisible although the element is still editable.

**Comment by TheFakeCake** [comment]
I did some digging and found the `-moz-user-modify` custom property of Firefox: https://developer.mozilla.org/en-US/docs/Web/CSS/user-modify

I tried using it with the `revert` value without success, but setting it with `read-write` works:

```css
:where([contenteditable]) {
  -moz-user-modify: read-write;
}
```

I am not sure this is the property that causes the bug though, since `-moz-user-modify: revert;` does nothing. Also I did not test this thoroughly.

The MDN doc states:

> Warning: This property has been replaced by the contenteditable attribute.

**Comment by elad2412** [comment]
Updated in the new version 1.4.1

Thanks for the update!
