### ISSUE TITLE
Could I use this css reset inside html email content?

### ISSUE THREAD

**Issue by BasicLich** [elad2412/the-new-css-reset#33]
I'm dealing with an issue that is our users are entering content into a WYSIWYG in a browser, and then that content ends up getting emailed to people. I'm trying to normalize the emails. I'm seeing things like ordered lists will be roman numerals some places but 123 numbers on other displays of the same content. Also some applications the table width will be as small as possible, and in other places the tables will have a min width applied. It's all over the place. I know this library doesn't say it supports email applications but I haven't been able to find anything closer.

**Comment by elad2412** [comment]
Email can use ancient browser engines like the old outlook version. Because of this, I don't think it is a good idea as an email template.

The main idea of this CSS reset is to use the cutting-edge features of browsers. Email apps like Outlook are the opposite of this.

The second thing the CSS reset removes everything so that you can customize your own lists design.

I hope this answers your question.
