### ISSUE TITLE
Problem with height of <select> in Safari

### ISSUE THREAD

**Issue by vhanadium** [elad2412/the-new-css-reset#35]
I have a <select> that I hide with
select {
  height: 0;
  overflow: hidden;
  opacity: 0;
  pointer-events: none;
}

But the height didn't apply until I add this :
select {white-space: pre;}

**Comment by elad2412** [comment]
Please add CodePen example and which version of Safar you are using.

I try to create your bug, but I didn't see any special thing.

**Comment by vhanadium** [comment]
hi here is an exemple: [https://codepen.io/vhanadium/pen/rNpxVrM](https://codepen.io/vhanadium/pen/rNpxVrM). You'll notice that the space of the select is still there. In my dev the word-space: pre did the trick but on codeine no that's strange.

**Comment by elad2412** [comment]
First, it isn't a bug of the CSS reset. Because with or without it works the same.

Second, the line-height is why you see the space, not only in Safari but also in all browsers.

If you want to remove the spacing, you need to reset line-height of the container to zero. I can't see the reason to do so, but you can.

I'm closing the issue. It isn't a bug of the CSS reset.

If I miss anything else, feel free to comment.
