### ISSUE TITLE
Reset makes hr vanish

### ISSUE THREAD

**Issue by raphaelgoetter** [elad2412/the-new-css-reset#51]
Hello,

`all: unset` resets all borders to zero, which makes `<hr>` tags disapear :

Codepen : https://codepen.io/raphaelgoetter/pen/rNvmWwY?editors=1100

**Comment by rku4er** [comment]
It doesn't seem to be true on my end:
![New-reset-and-hr](https://user-images.githubusercontent.com/5741713/190925728-6e078f96-9095-4836-9cde-d7e3657f7512.png)

**Comment by graymatter00** [comment]
Hi @raphaelgoetter,

I believe what you are seeing is the intended result.  That is, resetting all CSS properties to their default (`inherited` or `initial`) values according to the HTML specification.

In the case of the `border` property on the `<hr>` tag, `all: unset` will set the `border-style` property to its `initial` value of `none`, resulting in no border being displayed.  The `initial` value is applied because the `border-*` properties do not `inherit` their values.

Refer to...
https://developer.mozilla.org/en-US/docs/Web/CSS/unset
https://developer.mozilla.org/en-US/docs/Web/CSS/initial
https://developer.mozilla.org/en-US/docs/Web/CSS/border

The intention is that after applying `the-new-css-reset`, you then set the desired CSS for the `<hr>` and all other relevant tags in your project.  Or, as explained by @elad2412 in the README.md, you could use `revert` to return the `<hr>` tag back to the default styles of the browser. Such as...

```
hr {
    all: revert;
}
```

**Comment by raphaelgoetter** [comment]
Hello,

Yes, I understood that the purpose of the reset was to reset the display of the elements... but in this case for this particular element the fact that it disappears completely is a real problem, no?
