### ISSUE TITLE
problem with counter-reset in nested lists (Firefox only)

### ISSUE THREAD

**Issue by jowra** [elad2412/the-new-css-reset#75]
Firefox has a problem with the numbering of nested ordered lists.

With the reset, the property "counter-reset" in Firefox is not set, so Firefox counts every list item continuously. All other browsers are using the standard: ol {counter-reset: list-item}, but for Firefox this must be explicitly set.

MWE:

[list.txt](https://github.com/elad2412/the-new-css-reset/files/12368050/list.txt)

**Comment by techmagus** [comment]
Oh! There's a report here already!

I encountered this as well.

In any case, I filed a bug report over at Firefox:

https://bugzilla.mozilla.org/show_bug.cgi?id=1881517

Hopefully they'll add `counter-reset: list-item` in their UA stylesheet.

**Comment by techmagus** [comment]
Update.

It's not a Firefox bug per se, Firefox does have `counter-reset: list-item` in its UA stylesheet. The problem, as they explained, is that the other browsers are not implementing lists as per the CSS spec.

To quote Emilio Cobos Álvarez (https://bugzilla.mozilla.org/show_bug.cgi?id=1881517#c4):

> Yeah, this is not really a regression from that change, and this is really invalid. Firefox implements CSS lists using CSS counters as per spec, so you're really resetting https://searchfox.org/mozilla-central/rev/a8cc31504a2379bcf8ba395d2da7bb632b5521d6/layout/style/res/html.css#570.
>
>The issue is that other browsers don't implement html lists using CSS.

The best solution then if using the `all` property is to also set:
```
ol { counter-reset: list-item; }
```

Since the `all` property reset the `counter-reset` property.
