### ISSUE TITLE
img should also have `height: auto;`

### ISSUE THREAD

**Issue by cadars** [elad2412/the-new-css-reset#9]
Considering the following common markup:
```html
<img src="image.jpg" width="800" height="600">
```

Because of `max-width: auto`, the image will be squished when the viewport gets smaller than 800px.

**Comment by elad2412** [comment]
Separate the two things:
1. it's ok to give dimensiuon for overflow reasons.
2. But if you don't give any dimension, there isn't any logic that we will want the image the overflow from the container.

But you are giving me an idea maybe to add the max-width only when the image doesn't have the width attribute.

Example:

```
img:where(:not([width])){
   max-width:100%;
}
```
But I need to think about it, because when you think responsive you make those adjustments of responsive are working.

**Comment by raphaelgoetter** [comment]
Hello,

Most (all?) of actual CMS (WordPress, etc.) or HTML frameworks will automatically add `width=` and `height=` attributes on all images injected by content writers, so `height: auto;` seems mandatory in my opinion.

**Comment by elad2412** [comment]
@raphaelgoetter ```height: auto;``` is already the default. The question here is if we need to consider ```max-height: 100%;```.

For now, I still don't see any real good reason to put as a feature for all developers in a CSS reset.

**Comment by raphaelgoetter** [comment]
Yep `height: auto;` is the default,... but it's always overwriten by the CMS and HTML frameworks when the import image and tag them with `width=` and `height=`.

EDIT : ohwait, but `* {all: unset;}` does the job and overwrites HTML `height=` attribute, does it?

**Comment by elad2412** [comment]
@raphaelgoetter, yes, it reset all the elements except the specific elements to ```width:auto; height:auto;```

**Comment by elad2412** [comment]
For now, this issue isn't looking necessary. Issue closed
